### ISSUE TITLE
Auto completions slow and incorrect

### ISSUE THREAD

**Issue by FeBe95** [pichillilorenzo/JavaScriptEnhancements#11]
### Expected Behavior
- auto complete suggestions show up based on the JS contexts

### Actual Behavior
- rather slow auto complete popups and/or wrong suggestions

### Screenshots (click to view in fullscreen)
![jsenhancements](https://user-images.githubusercontent.com/7470739/34748074-2a8709f2-f59b-11e7-8f86-7ad489e7eee9.gif)

- although I typed rather slowly for the demo, the popups are delayed quite a bit, which makes the plugin inconvenient to use
- when using backspace JSE thinks it still should suggest options for `element.style.suggestion_here` and thus displayes `outlineStyle` etc.

### Specifications
- Sublime Text 3 build: 3143
- OS: Windows 64bit
- JavaScript Enhancements version: 0.11.1

I am really looking forward to seeing this plugin in its final state!

**Comment by pichillilorenzo** [comment]
@FeBe95 I released a new version for both issues! Let me know if now it works better!

**Comment by FeBe95** [comment]
Definitely better now, but still not "instant" as is used to be, but perfectly fine to use now! Getting some different errors now, I am going to update the other issue soon. Thanks for the time you invest in these issues!

**Comment by pichillilorenzo** [comment]
@FeBe95 I know about the "instant" but the problem is that the Flow server didn't support yet a persistent connection 😞 . They are developing it but it is not ready yet.

In fact if you install [flow](https://github.com/facebook/flow) and you run `flow --help`, you will see near `ide`:

> Starts a persistent connection to the server. Currently in development and highly unstable

So we must wait for it. However completions on my machine are not a problem! Maybe there are some performance difference on the different flow binaries.
